<Project Sdk="Microsoft.NET.Sdk">
<PropertyGroup><TargetFramework>net6.0</TargetFramework><AssemblyName>BoneLib</AssemblyName><GenerateAssemblyInfo>false</GenerateAssemblyInfo></PropertyGroup>
<ItemGroup><ProjectReference Include="../StubMarrow/StubMarrow.csproj" /><PackageReference Include="UnityEngine.Modules" Version="2021.3.16" /><PackageReference Include="LavaGang.MelonLoader" Version="0.7.2" /></ItemGroup>
</Project>